version: '3.8'

# Servicios
services:

  nginx:
    image: nginx:1.21-alpine
    ports:
      - "80:80"
    volumes:
      - "./src/${BACKEND_REPO}:/var/www/backend"
      - ./.docker/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - backend

  backend:
    build:
      context: "./src/${BACKEND_REPO}"
      args:
        HOST_UID: $HOST_UID
    working_dir: /var/www/backend
    volumes:
      - "./src/${BACKEND_REPO}:/var/www/backend"
      - ./.docker/backend/init:/opt/files/init
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  frontend:
    build:
      context: "./src/${BACKEND_REPO}/frontend"
      args:
        HOST_UID: $HOST_UID
    working_dir: /var/www/backend
    volumes:
      - "./src/${BACKEND_REPO}:/var/www/backend"
    depends_on:
      - backend

  postgres:
    image: postgres:12-alpine
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: 2522
      POSTGRES_DB: arbil
      POSTGRES_USER: arbil
    volumes:
      - pgsqldata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:alpine
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 1s
      timeout: 3s
      retries: 30

volumes:
  pgsqldata: